name: Trigger AWS Deploy
on:
  push:
    branches:
      - 'main'
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: up
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SLOTH_WEBHOOK: ${{ secrets.SLOTH_WEBHOOK }}
          CSTEAM_WEBHOOK: ${{ secrets.CSTEAM_WEBHOOK }}
        run: |
          echo "SLOTH_WEBHOOK=$SLOTH_WEBHOOK" >> ./.env
          echo "CSTEAM_WEBHOOK=$CSTEAM_WEBHOOK" >> ./.env
          mkdir ~/.aws
          echo "[weka-deploy]" > ~/.aws/credentials
          echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
          echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY"  >> ~/.aws/credentials
          echo "[profile weka-deploy]" > ~/.aws/config
          echo "region=ap-southeast-2" >> ~/.aws/config
          npm install
          npx arc env production SLOTH_WEBHOOK $SLOTH_WEBHOOK
          npx arc env production CSTEAM_WEBHOOK $CSTEAM_WEBHOOK
          npm run deploy --production
